### ISSUE TITLE
xinetd / inetd issues

### ISSUE THREAD

**Issue by gnosoz** [munin-monitoring/muninlite#1]
May I suggest an easier installation process with a script that install any missing package and then performs the configuration maybe requesting the user for 2 variables: PORT_munin_server and IP_munin_server.
It should never touch the iptables or maybe request if the firewall rules needs to applied or not.

I am few days struggling with xinetd and inetd that will not start regardless of what is done to them, I think this issue should be checked properly.

I am thinking of trying out to use the ssh workaround unless you have any suggestion on regards with xinetd or inetd not starting?

I am using a branch of the openwrt and is equipped with busybox

**Comment by sumpfralle** [comment]
Your thoughts are very welcome!

Maybe you could describe a bit more in detail, how you use and install muninlite at the moment.

Personally I am used to installing it via OpenWrt's package (the new muninlite version was recently merged into master). After the installation *it just works* for me. I.e. I can access it via port 4949 via the LAN interface.

Did you have something else in mind?

**Comment by gnosoz** [comment]
Hi sumpfralle. great job on this muninlite project and thanks for maintaning it
In my situation both xinetd and inetd failed but I resolved with this install script that if you want you can merge freely as I release it with GPL 3.0 licence

I noticed you mention everywhere that files are in /usr/local/sbin/muninlite whilst I noticed in all installs I performed that it created it in /usr/sbin/muninlite



#!/bin/bash
# Copyright Taurus Bond Srl
# Released under licence GPL 3.0
# this script doesn't insert firewall rules as those are specific for each system / setup
# be careful to accept incoming connections to this port only from the authorized munin master

opkg update && opkg install muninlite
echo "
# Copyright Taurus Bond Srl
# Released under licence GPL 3.0
START=10
STOP=15
start() {
        # commands to launch application and leave it in background
	/usr/sbin/muninlite &
}
stop() {
        killall muninlite
        # commands to kill application
}
restart() {
        killall muninlite
        /usr/sbin/muninlite &
        # commands to kill application
}
" >  /etc/init.d/muninlite

# creation link in rc.d to autostart at boot time in position S60 is optimal as it 
# launch muninlite after all essential services are already operative
ln -s /etc/init.d/muninlite /etc/rc.d/S60muninlite
chmod +x /etc/init.d/muninlite

# Insert service as it is never found there
echo "muninlite       4950/tcp        lrrd    # muninlite" >> /etc/services

**Comment by sumpfralle** [comment]
> great job on this muninlite project and thanks for maintaning it

Thanks! :)

In fact I am only maintaining it for some months now. Most of the work was done by *runesk* before.

> In my situation both xinetd and inetd failed

Do you use the current OpenWrt master branch? Or some other packaging?

I think, muninlite as packaged for OpenWrt should just work out of the box. If you notice a problem with OpenWrt's packaging, then you could report it [in their issue tracker](https://github.com/openwrt/packages/issues). But you can also report it here, since I am somehow maintaining that packaging, too.

> I noticed you mention everywhere that files are in /usr/local/sbin/muninlite whilst I noticed in all installs I performed that it created it in /usr/sbin/muninlite

Yes, there are two common ways of installing software:
* from source
* packaged

The muninlite package distributed by OpenWrt is *packaged*. Here the package maintainer decides where to put the files based on the preferences of the distribution. In OpenWrt this is `/usr/sbin/muninlite`.

The installation *from source* (via `make install` in the repository directory) traditionally installs files below `/usr/local/...`. This keeps manually installed software separated from packaged software. I think, this is a well established convention for a few decades. I am used to projects using the *from source* paths in documentation, thus I did it here, too (and it was that way before I started to maintain muninlite). I understand, that this can be surprising, but I am not aware of an alternative.

Regarding your script proposal:

> ` #!/bin/bash`

Are you sure, that `bash` is installed on your OpenWrt-based device? (the above script also runs with `sh`)

> /usr/sbin/muninlite &

The line above starts the `muninlite`, which is waiting for requests on STDIN and writing its output to STDOUT. But in the context of a system service (as it is in the above init script), it should really not do anything useful, I think. Are you sure, that this init script has a noticable effect?

The muninlite packaging in OpenWrt instead just adds the relevant [xinetd configuration file](https://github.com/openwrt/packages/blob/master/admin/muninlite/files/etc/xinetd.d/muninlite). This is everything that is needed to let it run automatically on demand.

> echo "muninlite       4950/tcp        lrrd    # muninlite" >> /etc/services

Here on my OpenWrt-based device (release 19.07) the line is already there:
```shell
$ grep munin /etc/services 
munin           4949/tcp
```

I am still a bit confused, in which specific environment you are experiencing issues. The OpenWrt packaging should really just work. I am curiously looking forward to more details :)

**Comment by gnosoz** [comment]
Hi @sumpfralle,
yes my system is indeed special as it is a branch of OpenWRT, I utilize the magical openMPTCProuter branch @Ysurac.
My system does have natively the bash but the script could easily be changed in /bin/ash for native busybox and to make it more general.

> /usr/sbin/muninlite &
> 
> The line above starts the muninlite, which is waiting for requests on STDIN and writing its output to STDOUT. But in the context of a system service (as it is in the above init script), it should really not do anything useful, I think. Are you sure, that this init script has a noticable effect?

I see your point as when you call /usr/sbin/muninlite it usually awaits for terminal commands but I noticed that once started it doesn't have a timeout and the service remains open to listen for streams from remote sources which is the whole purpose of a system service so for me that is a job accomplished :)

Not sure if is worth adding some lines in the code to add some checks on regards with which type of service deamon configure in each system and apply xinetd, init.d or inet based on that.

Would definitely be great for the system to automatically configure the firewall based on which one is installed although this would need for the user to specify IP of the munin master somehow.

in my case for example I just configure it as follows [  I know is rudimentary but works and is persistent  :))  heheh ]

```

# Creation firewall rules
#	to allow muninlite to be contacted by master 
# 	to allow client to access master webserver for statistics
if [grep "munin" /etc/config/firewall]; then
echo "Failed - firewall rules already loaded in /etc/config/firewall"
else
echo "
config redirect                               
        option dest_port 'XYZ'                              
        option src 'lan'                    
        option src_dport 'XYZ'                                                                                      
        option target 'DNAT'                 
        option dest_ip 'XXXXXXXXX'           
        option dest 'vpn'                     
        list proto 'tcp'                                   
        option name 'munin_webserver'       
                                                                                                                     
config redirect                              
        option src 'vpn'                        
        option name 'munin_node_router'       
        option target 'DNAT'                               
        option dest_ip '192.168.100.1'      
        option dest 'lan'                                                                                            
        option dest_port '4950'              
        option src_dport 'XXXX'                
>> /etc/config/firewall

	# restart the firewall to apply rules
	/etc/init/firewall stop
	/etc/init/firewall start
	echo "OK - Firewall rules for muninlite and munin web server access configured"
fi	
```

**Comment by sumpfralle** [comment]
> I see your point as when you call /usr/sbin/muninlite it usually awaits for terminal commands but I noticed that once started it doesn't have a timeout and the service remains open to listen for streams from remote sources [..]

I think, you misunderstand this. Calling `muninlite` directly (without connecting its stdin and stdout to something else) is not related to any external requests (e.g. via TCP). This process would just sit there forever without doing any kind of work (easily to be verified by running `strace -f muninlite`). Please correct me, if we are talking about different things here.

btw: which kind of *timeouts* do you refer to?

> Would definitely be great for the system to automatically configure the firewall based on which one is installed although this would need for the user to specify IP of the munin master somehow.

Requests from the *inside* (i.e. the `LAN` zone) are allowed by default (in OpenWrt). Regarding the IP of the munin master: `muninlite` does not implement any kind of access control (in contrast to the proper `munin-node` implementation). Everyone may talk to it, as long as the firewall rules allow that.

> \# Creation firewall rules
> [..]

I am confused, that you are suggesting `DNAT` redirects here.
Do you want to open the `muninlite` TCP port for specific requests from the `vpn` interface? This looks like a custom configuration, which cannot really be applied to *all* users of the `muninlite` package. Or did you mean something else?

Regarding your manipulation of the firewall rules: `uci set` is probably the cleaner approach to do this.

> /etc/init/firewall stop
> /etc/init/firewall start

Personally I prefer `reload_config` for such actions. But that is just a matter of taste ...

**Comment by sumpfralle** [comment]
I think, the current setup for OpenWrt is working. Thus I am closing this bug report.

Feel free to re-open it, if you see something that could be improved.

**Comment by Neustradamus** [comment]
@gnosoz: What is the current situation?
